
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  
  
  config.vm.define "server1" do |web|
    web.vm.hostname = "server1"
    web.vm.network "private_network", ip: "192.168.56.17"
  end
  
  config.vm.define "server2" do |db|
    db.vm.hostname = "server2"
    db.vm.network "private_network", ip: "192.168.56.18"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.usable_port_range = (8000..9000)
end
